# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-13 12:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breakfast', models.CharField(max_length=200)),
                ('lunch', models.CharField(max_length=200)),
                ('dinner', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Menu_mon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Day')),
            ],
        ),
        migrations.CreateModel(
            name='Menu_tue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Day')),
            ],
        ),
        migrations.CreateModel(
            name='MessMaharaj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maharaj_name', models.CharField(max_length=30)),
                ('maharaj_dp', models.ImageField(upload_to='')),
                ('maharaj_mailid', models.EmailField(max_length=254)),
                ('maharaj_mess', models.CharField(max_length=30)),
                ('maharaj_mob', models.CharField(max_length=10)),
            ],
        ),
    ]
