# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-13 15:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu_fri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Day')),
            ],
        ),
        migrations.CreateModel(
            name='Menu_sat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Day')),
            ],
        ),
        migrations.CreateModel(
            name='Menu_sun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Day')),
            ],
        ),
        migrations.CreateModel(
            name='Menu_thr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Day')),
            ],
        ),
        migrations.CreateModel(
            name='Menu_wed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Day')),
            ],
        ),
    ]
