# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-14 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20161114_0222'),
    ]

    operations = [
        migrations.AddField(
            model_name='usr_profile',
            name='user_email',
            field=models.EmailField(default=b'abc@gmail.com', max_length=254),
        ),
    ]
