# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-14 19:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_usr_profile_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='name',
            field=models.CharField(default=b'not_set', max_length=10),
        ),
        migrations.AlterField(
            model_name='usr_profile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
